spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: postgres
  application:
    name: StudentManager
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true
    changeLog: liquibase/master.xml

server:
  error:
    include-message: always
  port: 9090